### ISSUE TITLE
Step with status: failure doesn't get triggered

### ISSUE THREAD

**Issue by wass3r** [go-vela/worker#82]
Consider the following pipeline:
```yaml
version: "1"

steps:
  - name: failing
    image: alpine:latest
    commands:
      - sleep 5 && echo "failing the build" && exit 1
  - name: run on failure
    image: alpine:latest
    ruleset:
      status: [failure,pending]
    commands:
      - echo "i show on build failure"
```
In this scenario the build fails successfully, but "run on failure" never runs.
