### ISSUE TITLE
Builds without steps should not spawn

### ISSUE THREAD

**Issue by davidvader** [go-vela/worker#90]
## Description

Vela should refrain from spawning builds that have no valid steps

### Steps to Reproduce
push to `master`

`vela.yml`:
```
steps:
  - name: dont_run
    image: golang:latest
    commands:
      - echo "do not run"
    ruleset:
      branch: [ nonexistent_branch ]
```

## Value

Reduce on builds, avoid false-negative status checks, etc

## Definition of Done

When a build should have no steps to run based on rulesets etc, that build should not be created
